name: auto-merge-dependabot
on:
  pull_request:
    branches:
      - development

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: staging # your chosen branch for Dependabot updates

      - name: auto-merge
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            
            if (pullRequest.user.login === 'dependabot[bot]' && pullRequest.mergeable) {
              const { data: mergeResult } = await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number
              })

              if (mergeResult.merged) {
                const branchName = pullRequest.head.ref;
                await github.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: 'heads/' + branchName
                });
              }
            }

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: development
          branch: 'staging'
          delete-branch: true
          title: 'Dependabot updates'
          body: 'This PR includes all Dependabot updates.'
