name: Generate and commit package-lock.json

on:
  push:
    branches: [ main, development ]

jobs:
  update-lockfile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory: ['server', 'tenant_frontend']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'

    - name: Generate package-lock.json
      run: |
        cd ${{ matrix.directory }}
        npm install

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'chore: update package-lock.json'
        file_pattern: ${{ matrix.directory }}/package-lock.json
        branch: ${{ github.head_ref }}
